### ISSUE TITLE
Missing admin user parameter on clean install

### ISSUE THREAD

**Issue by alinalexandru** [davidalger/warden-env-magento2#15]
At least on Magento 2.2.X, the admin parameters needs to be set when installing the application.

I'll investigate more, and come with a PR.

**Comment by davidalger** [comment]
@alinalexandru I'm going to go ahead and close this. You're welcome to modify to suite you're needs, but not sure accepting a PR with changes to support a version of Magento that is well beyond it's EOL makes much sense.
