### ISSUE TITLE
required authentication error

### ISSUE THREAD

**Issue by hitchho** [davidalger/warden-env-magento2#5]
I'm trying to install template with magento2 on my debian10 based VPS, but receiving following error when running init.sh --clean-install. auth.json is configured right to webroot.  Have only changed .env values to my domain name. 

This should work without composer being locally installed right?

```
==> [18:20:23] Installing meta-package

                                                                             
  [Composer\Downloader\TransportException]                                   
  The 'https://repo.magento.com/packages.json' URL required authentication.  
  You must be using the interactive console to authenticate                  
                                                                             

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

ERROR: Command `warden env exec -T php-fpm composer create-project -q --no-interaction --prefer-dist --no-install --repository-url=https://repo.magento.com/ "${META_PACKAGE}" /tmp/create-project "${META_VERSION}"` on line 207 failed with exit code 255

```

**Comment by davidalger** [comment]
This should work without composer installed on the host machine; tested that myself on a Fedora box I've got (which has no composer installed). The composer command being called is being run inside the php-fpm container.

The error message shown above would seem to indicate the credentials in `./webroot/auth.json` are not working, or perhaps that the Marketplace was having a transient issue (I've seen this authentication failure running a simple `composer install` on a project, and running it again the issue resolved itself).

If you run `warden shell` to get inside the FPM container and run the `composer create-project` manually it is effectively the same thing the script is doing.

Only thing I can suggest is make sure your `./webroot/auth.json` file looks like this, and perhaps double check the keys in it match what's in an active Magento.com account.

```json
{
    "http-basic": {
        "repo.magento.com": {
            "username": "<public_key>",
            "password": "<private_key>"
        }
    }
}
```

**Comment by hitchhooker** [comment]
thanks a lot for your reply. seems that composer.json is required for template to work. 

solved problem with your tip
`warden shell
sudo composer global config http-basic.repo.magento.com account password`
