### ISSUE TITLE
`warden bootstrap` throwing an error

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden-env-magento2#9]
I am trying to install Magento 2 with your #warden tool.
But stuck with the below issue when I run the `warden bootstrap` command

> invalid option ../.warden/commands/bootstrap.cmd: line 3: set: pipefail
` at ../.warden/commands/bootstrap.cmd:3 failed with exit code 2

FYI, I am using MacOS with #bash version - 5.0.18

**Comment by davidalger** [comment]
@MagePsycho 
I'm afraid I'm not sure how to help you out here very much. The shebang for Warden's entrypoint specifies bash as the interpretter and pipefail is a standard bash option. The only shell that I know of which doesn't know about it in fact is `dash`:
```
davidalger@mac-mini:~$ /usr/bin/env bash -c 'set -o pipefail'
davidalger@mac-mini:~$ /usr/bin/env bash --posix -c 'set -o pipefail'
davidalger@mac-mini:~$ /usr/bin/env sh -c 'set -o pipefail'
davidalger@mac-mini:~$ /usr/bin/env ksh -c 'set -o pipefail'
davidalger@mac-mini:~$ /usr/bin/env zsh -c 'set -o pipefail'
davidalger@mac-mini:~$ /usr/bin/env dash -c 'set -o pipefail'
dash: 1: set: Illegal option -o pipefail
davidalger@mac-mini:~$ 
```

Is it possible that `bash` is actually launching a non-bash interpretter on your system?

**Comment by MagePsycho** [comment]
@davidalger CRLF was causing the issue. After configuring the git as
```
git config --global core.autocrlf input
```
and cloning the repo, fixed the issue.

**Comment by davidalger** [comment]
Interesting! And also a bit strange. Thanks for sharing the solution.
